---
ros_api_user: ansible
ros_api_password: P@ssw0rd
ansible_connection: "ansible.builtin.local"

bridge:
  name: bridge
  vlan:
    - vlanid: 100
      comment: Management VLAN
    - vlanid: 110
      comment: WiFi Access Points
    - vlanid: 120
      comment: VTZS
    - vlanid: 130
      comment: SKUD