---
ros_api_user: ansible
ros_api_password: "Fycb,kz!"
ansible_connection: "ansible.builtin.local"

bridge:
  name: bridge
bridge_vlan:
  - vlanid: 100
    comment: Management
  - vlanid: 110
    comment: VTZS
  - vlanid: 120
    comment: SKUD
  - vlanid: 130
    comment: WiFi Access Points
