---
# BR01 switch ports specific settings
bridge_port:
  - name: ether1
    comment: Trunk port
    pvid: 10
    tagged: [10,11,20,30,40,50,60,70,80,90]
  - name: ether2
    comment: Trunk port
    pvid: 10
    tagged: [10,11,20,30,40,50,60,70,80,90]
  - name: ether3
    comment: Trunk port
    pvid: 10
    tagged: [10,11,20,30,40,50,60,70,80,90]
  - name: ether4
    comment: Trunk port
    pvid: 10
    tagged: [10,11,20,30,40,50,60,70,80,90]
  - name: ether5
    comment: Trunk port
    pvid: 10
    tagged: [10,11,20,30,40,50,60,70,80,90]
  - name: ether6
    comment: Trunk port
    pvid: 10
    tagged: [10,11,20,30,40,50,60,70,80,90]
  - name: ether7
    comment: Trunk port
    pvid: 10
    tagged: [10,11,20,30,40,50,60,70,80,90]
  - name: ether8
    comment: Trunk port
    pvid: 10
    tagged: [10,11,20,30,40,50,60,70,80,90]
  - name: ether9
    comment: Trunk port
    pvid: 10
    tagged: [10,11,20,30,40,50,60,70,80,90]
  - name: ether10
    comment: Trunk port
    pvid: 10
    tagged: [10,11,20,30,40,50,60,70,80,90]
  - name: ether11
    comment: Trunk port
    pvid: 10
    tagged: [10,11,20,30,40,50,60,70,80,90]
  - name: ether12
    comment: Management port
    pvid: 10
    edge: yes
    loop-protect: on
  - name: ether13
    comment: Management port
    pvid: 10
    edge: yes
    loop-protect: on
  - name: sfp-sfpplus2
    comment: USWSTAGE
    pvid: 10
    tagged: [10,11,20,30,40,50,60,70,80,90]
  - name: sfp-sfpplus3
    comment: Trunk port
    pvid: 10
    tagged: [10,11,20,30,40,50,60,70,80,90]
  - name: sfp-sfpplus4
    comment: Trunk port
    pvid: 10
    tagged: [10,11,20,30,40,50,60,70,80,90]