---
# Main configuration file
- hosts: switches-ros7,!dns-servers
  tasks:
  - name: Set DNS servers
    community.routeros.api_modify:
      hostname: "{{ address }}"
      password: "{{ ros_api_password }}"
      username: "{{ ros_api_user }}"
      path: ip dns
      data:      
        - servers: "10.10.0.2,10.10.0.3"
        
- hosts: switches-ros7
  gather_facts: false
  
  roles:
    - ros7_switch
  tasks:
  - name: Set NTP server
    community.routeros.api_modify:
      hostname: "{{ address }}"
      password: "{{ ros_api_password }}"
      username: "{{ ros_api_user }}"
      path: system ntp client servers
      data:      
        - address: "pool.ntp.org"

  - name: Enable NTP client
    community.routeros.api_modify:
      hostname: "{{ address }}"
      password: "{{ ros_api_password }}"
      username: "{{ ros_api_user }}"
      path: system ntp client
      data:      
        - enabled: "yes"

  - name: Add prometheus access group
    community.routeros.api_modify:
      hostname: "{{ address }}"
      password: "{{ ros_api_password }}"
      username: "{{ ros_api_user }}"
      path: user group
      data:      
        - name: "prometheus"
          policy: "read,api"
    tags: prometheus
  
  - name: Add prometheus user
    community.routeros.api_modify:
      hostname: "{{ address }}"
      password: "{{ ros_api_password }}"
      username: "{{ ros_api_user }}"
      path: user
      data:      
        - name: "prometheus"
          group: "prometheus"
          password: !vault |
                    $ANSIBLE_VAULT;1.1;AES256
                    61616431653639316463613533336234363262343239656665356235396634633364383264623664
                    3865646165343634303763636562373038666636366534660a623265393438616163643361303638
                    38616536643263306532343766636633346264363930343863373939336566663965653333313061
                    3061326439343530620a303135616331616265383265643138613039383963393231616361623062
                    3937
    tags: prometheus
  
  - name: Get all ethernet interfaces
    community.routeros.api_info:
      hostname: "{{ address }}"
      password: "{{ ros_api_password }}"
      username: "{{ ros_api_user }}"
      path: interface ethernet
    register: interfaces
    tags: storm
  
  - name: Set storm rate
    community.routeros.api_find_and_modify:
      hostname: "{{ address }}"
      password: "{{ ros_api_password }}"
      username: "{{ ros_api_user }}"
      path: interface ethernet switch port
      find:
        # name: "{{ item.name }}"
        switch: "switch1"
      values:        
        limit-unknown-multicasts: yes
        limit-unknown-unicasts: yes
        storm-rate: 5
    # loop: "{{ interfaces.result }}"


- hosts: dhcp-servers
  gather_facts: false
  
  roles:
    - ros7_dhcp_server

- hosts: dns-servers
  tasks:
    # - name: Get all static DNS records
    #   community.routeros.api_info:
    #   hostname: "{{ address }}"
    #   password: "{{ ros_api_password }}"
    #   username: "{{ ros_api_user }}"
    #   path: ip dns static
    #   register: dnsrr
    #   tags: dns
    
    - name: DNS Server - Add A records
      community.routeros.api_modify:
        hostname: "{{ address }}"
        password: "{{ ros_api_password }}"
        username: "{{ ros_api_user }}"
        path: ip dns static
        data:
          - name: R01
            address: 10.10.0.2
          - name: R02
            address: 10.10.0.3
          - name: SW01
            address: 10.10.0.4
          - name: SW02
            address: 10.10.0.5
          - name: SW1DC01
            address: 10.10.0.6
          - name: SW1DC02
            address: 10.10.0.7
          - name: USW1C
            address: 10.10.0.11
          - name: USW1A
            address: 10.10.0.12
          - name: USW1D
            address: 10.10.0.13
          - name: USW1F
            address: 10.10.0.14
          - name: USW1E
            address: 10.10.0.15
          - name: USW2A
            address: 10.10.0.21
          - name: USW2H
            address: 10.10.0.22
          - name: USW2D
            address: 10.10.0.23
          - name: USW2C
            address: 10.10.0.27
          - name: USW2F
            address: 10.10.0.28
          - name: USW3E
            address: 10.10.0.31
          - name: USW3F
            address: 10.10.0.32
          - name: USW3M
            address: 10.10.0.33
          - name: USW3K
            address: 10.10.0.36
          - name: USW3R
            address: 10.10.0.37
          - name: USW3P
            address: 10.10.0.38
          - name: USW4C
            address: 10.10.0.41
          - name: USW4D
            address: 10.10.0.42
          - name: USW4E
            address: 10.10.0.43
          
          
          
      tags: dns

    

    
