---
# Main configuration file
- hosts: trans_ros7
  gather_facts: false
  
  roles:
    - ros7_switch

# - hosts: ros7
#   tasks:
#     - name: Display all variables/facts known for a host
#       debug:
#         var: hostvars[inventory_hostname]
#       tags: debug_info

    

    
