---
- name: Create DHCP address pool
  community.routeros.api_modify:
    hostname: "{{ address }}"
    password: "{{ ros_api_password }}"
    username: "{{ ros_api_user }}"
    path: "ip pool"
    data:
      - name: "{{ item.pool.name }}"
        ranges: "{{ item.pool.ranges | join(',') }}"
  loop: "{{ dhcp_server }}"
  tags: pool



- name: Configure DHCP network options
  community.routeros.api_modify:
    hostname: "{{ address }}"
    username: "{{ ros_api_user }}"
    password: "{{ ros_api_password }}"
    path: "ip dhcp-server network"
    data:
      - address: "{{ item.network }}"
        gateway: "{{ item.default_gateway }}"
        dns-server: "{{ item.dns }}"
  loop: "{{ dhcp_server }}"
  tags: network

- name: Get DHCP servers list
  community.routeros.api_info:
    hostname: "{{ address }}"
    username: "{{ ros_api_user }}"
    password: "{{ ros_api_password }}"
    path: "ip dhcp-server"
  register: dhcp_servers_list

- name: Print dhcp_servers_list
  ansible.builtin.debug:
    var: dhcp_servers_list

- name: Modify DHCP server
  community.routeros.api_find_and_modify:
    hostname: "{{ address }}"
    username: "{{ ros_api_user }}"
    password: "{{ ros_api_password }}"
    path: "ip dhcp-server"
    find:
      interface: "{{ item.interface }}"
    values:
      name: "{{ item.name }}"
      interface: "{{ item.interface }}"
      address-pool: "{{ item.pool.name }}"
      lease-time: "{{ item.lease_time }}"
  when: dhcp_servers_list.result | selectattr("interface","equalto",item.interface) | list | length != 0
  loop: "{{ dhcp_server }}"
  tags: server

- name: Create DHCP server
  community.routeros.api_modify:
    hostname: "{{ address }}"
    username: "{{ ros_api_user }}"
    password: "{{ ros_api_password }}"
    path: "ip dhcp-server"
    data:
      - name: "{{ item.name }}"
        interface: "{{ item.interface }}"
        address-pool: "{{ item.pool.name }}"
        lease-time: "{{ item.lease_time }}"
  when: dhcp_servers_list.result | selectattr("interface","equalto",item.interface) | list | length == 0
  loop: "{{ dhcp_server }}"
  tags: server