---
# CRS309-1G-8S+ SW216-1 specific settings
bridge_port:
  - name: sfp-sfpplus1
    comment: Default Config
    pvid: 10
    tagged: [10,11,20,30,40,50,60,70,80,90]
  - name: sfp-sfpplus2
    comment: Default Config
    pvid: 10
    tagged: [10,11,20,30,40,50,60,70,80,90]
  - name: sfp-sfpplus3
    comment: Default Config
    pvid: 10
    tagged: [10,11,20,30,40,50,60,70,80,90]
  - name: sfp-sfpplus4
    comment: Default Config
    pvid: 10
    tagged: [10,11,20,30,40,50,60,70,80,90]
  - name: sfp-sfpplus5
    comment: Default Config
    pvid: 10
    tagged: [10,11,20,30,40,50,60,70,80,90]
  - name: sfp-sfpplus6
    comment: Default Config
    pvid: 10
    tagged: [10,11,20,30,40,50,60,70,80,90]
  - name: sfp-sfpplus7
    comment: Default Config
    pvid: 10
    tagged: [10,11,20,30,40,50,60,70,80,90]
  - name: sfp-sfpplus8
    comment: Default Config
    pvid: 10
    tagged: [10,11,20,30,40,50,60,70,80,90]  
  - name: ether1
    comment: Default Config
    pvid: 10
    tagged: [10,11,20,30,40,50,60,70,80,90]