---
# SWG01 specific settings
bridge_port:
  - name: qsfpplus1-1
    comment: Trunk port
    pvid: 10
    tagged: [10,11,20,30,40,50,60,70,80,90]
  - name: qsfpplus1-2
    comment: Trunk port
    pvid: 10
    tagged: [10,11,20,30,40,50,60,70,80,90]
  - name: qsfpplus1-3
    comment: Trunk port
    pvid: 10
    tagged: [10,11,20,30,40,50,60,70,80,90]
  - name: qsfpplus1-4
    comment: Trunk port
    pvid: 10
    tagged: [10,11,20,30,40,50,60,70,80,90]
  - name: qsfpplus2-1
    comment: Trunk port
    pvid: 10
    tagged: [10,11,20,30,40,50,60,70,80,90]
  - name: qsfpplus2-2
    comment: Trunk port
    pvid: 10
    tagged: [10,11,20,30,40,50,60,70,80,90]
  - name: qsfpplus2-3
    comment: Trunk port
    pvid: 10
    tagged: [10,11,20,30,40,50,60,70,80,90]
  - name: qsfpplus2-4
    comment: Trunk port
    pvid: 10
    tagged: [10,11,20,30,40,50,60,70,80,90]
  - name: sfp-sfpplus1
    comment: R01
    pvid: 10
    tagged: [10,11,20,30,40,50,60,70,80,90]
  - name: sfp-sfpplus2
    comment: R02
    pvid: 10
    tagged: [10,11,20,30,40,50,60,70,80,90]
  - name: sfp-sfpplus3
    comment: SWE01
    pvid: 10
    tagged: [10,11,20,30,40,50,60,70,80,90]
  - name: sfp-sfpplus4
    comment: SWE02
    pvid: 10
    tagged: [10,11,20,30,40,50,60,70,80,90]
  - name: sfp-sfpplus5
    comment: USWG1B-sfpplus2
    pvid: 10
    tagged: [10,11,20,30,40,50,60,70,80,90]
  - name: sfp-sfpplus6
    comment: USWG2A
    pvid: 10
    tagged: [10,11,20,30,40,50,60,70,80,90]
  - name: sfp-sfpplus7
    comment: USWG3B
    pvid: 10
    tagged: [10,11,20,30,40,50,60,70,80,90]
  - name: sfp-sfpplus8
    comment: USWG4A
    pvid: 10
    tagged: [10,11,20,30,40,50,60,70,80,90]
  - name: sfp-sfpplus9
    comment: USWG4B
    pvid: 10
    tagged: [10,11,20,30,40,50,60,70,80,90]
  - name: sfp-sfpplus10
    comment: Main Stage
    pvid: 10
  - name: sfp-sfpplus11
    comment: USWGBKZ
    pvid: 10
    tagged: [10,11,20,30,40,50,60,70,80,90]
  - name: sfp-sfpplus12
    comment: USWG5A
    pvid: 10
    tagged: [10,11,20,30,40,50,60,70,80,90]
  - name: sfp-sfpplus13
    comment: USWG5B
    pvid: 10
    tagged: [10,11,20,30,40,50,60,70,80,90]
  - name: sfp-sfpplus14
    comment: USWG7A
    pvid: 10
    tagged: [10,11,20,30,40,50,60,70,80,90]
  - name: sfp-sfpplus15
    comment: USWG7B
    pvid: 10
    tagged: [10,11,20,30,40,50,60,70,80,90]
  - name: sfp-sfpplus16
    comment: USWG3A
    pvid: 10
    tagged: [10,11,20,30,40,50,60,70,80,90]
  - name: sfp-sfpplus17
    comment: Trunk port
    pvid: 10
    tagged: [10,11,20,30,40,50,60,70,80,90]
  - name: sfp-sfpplus18
    comment: Trunk port
    pvid: 10
    tagged: [10,11,20,30,40,50,60,70,80,90]
  - name: sfp-sfpplus19
    comment: Trunk port
    pvid: 10
    tagged: [10,11,20,30,40,50,60,70,80,90]
  - name: sfp-sfpplus20
    comment: Trunk port
    pvid: 10
    tagged: [10,11,20,30,40,50,60,70,80,90]
  - name: sfp-sfpplus21
    comment: USWB02
    pvid: 10
    tagged: [10,11,20,30,40,50,60,70,80,90]
  - name: sfp-sfpplus22
    comment: Trunk port
    pvid: 10
    tagged: [10,11,20,30,40,50,60,70,80,90]
  - name: sfp-sfpplus23
    comment: Trunk port
    pvid: 10
    tagged: [10,11,20,30,40,50,60,70,80,90]
  - name: sfp-sfpplus24
    comment: Trunk port
    pvid: 10
    tagged: [10,11,20,30,40,50,60,70,80,90]