---
# UR01 specific settings
bridge_port:
  - name: ether1
    comment: Ansible Host
    pvid: 100
  - name: sfp-sfpplus3
    comment: Trunk port
    pvid: 100
    tagged: [100,110,120,130,140,150,160.170,180,190]
  - name: sfp-sfpplus4
    comment: Trunk port
    pvid: 100
    tagged: [100,110,120,130,140,150,160.170,180,190]