---
# UR02 specific settings

dhcp_server:
  - name: VLAN110
    interface: "VLAN110"
    network: "10.110.0.0/16"
    dns: "10.110.0.2,10.110.0.3"
    default_gateway: "10.110.0.1"
    lease_time: "1h"
    pool:
      name: DHCP-VLAN110
      ranges:
        - "10.110.0.65-10.110.127.255"
#          - "10.100.128.0-10.100.255.254"

bridge_port:
  - name: ether1
    comment: Ansible Host
    pvid: 110
  - name: sfp-sfpplus3
    comment: Trunk port
    pvid: 110
    tagged: [110,120,130,140,150,160.170,180,190]
  - name: sfp-sfpplus4
    comment: Trunk port
    pvid: 110
    tagged: [110,120,130,140,150,160.170,180,190]