---
# CRS326-24G-2S+ USW1C specific settings
bridge_port:
  - name: ether1
    comment: 1C-C-19 STOLB A5000 Unifi U6E03
    pvid: 10
    tagged: [20, 30, 40, 50, 60, 70, 80, 90, 100]
  - name: ether2
    comment: 1C-C-14 STOLB A5000
    pvid: 20
  - name: ether3
    comment: 1C-C-17 A5000 LUYK
    pvid: 20
  - name: ether4
    comment: 1C-C-20 STOLB A5000
    pvid: 20
  - name: ether5
    comment: 1C-E-5 - 4th floor - U6Mxx
    pvid: 10
    tagged: [11, 20, 30, 40, 50, 60, 70, 80, 90, 100]
  - name: ether6
    comment: 1C-C-18 A5000 LUYK
    pvid: 20
  - name: ether7
    comment: 1C-E-7 - 4th floor - U7PMxx
    pvid: 10
    tagged: [11, 20, 30, 40, 50, 60, 70, 80, 90, 100]
  - name: ether8
    comment: 1C-E-8 - 4th floor - Pult
    pvid: 50
  - name: ether9
    comment: Default Config
    pvid: 50
  - name: ether10
    comment: Default Config
    pvid: 50
  - name: ether11
    comment: Default Config
    pvid: 50
  - name: ether12
    comment: Default Config
    pvid: 50
  - name: ether13
    comment: Default Config
    pvid: 50
  - name: ether14
    comment: Default Config
    pvid: 50
  - name: ether15
    comment: Default Config
    pvid: 50
  - name: ether16
    comment: Default Config
    pvid: 50
  - name: ether17
    comment: Trunk Native VLAN 10
    pvid: 10
    tagged: [20, 30, 40, 50, 60, 70, 80, 90, 100]
  - name: ether18
    comment: Trunk Native VLAN 10
    pvid: 10
    tagged: [20, 30, 40, 50, 60, 70, 80, 90, 100]
  - name: ether19
    comment: Trunk Native VLAN 10
    pvid: 10
    tagged: [20, 30, 40, 50, 60, 70, 80, 90, 100]
  - name: ether20
    comment: Trunk Native VLAN 10
    pvid: 10
    tagged: [20, 30, 40, 50, 60, 70, 80, 90, 100]
  - name: ether21
    comment: Trunk Native VLAN 10
    pvid: 10
    tagged: [20, 30, 40, 50, 60, 70, 80, 90, 100]
  - name: ether22
    comment: Trunk Native VLAN 10
    pvid: 10
    tagged: [20, 30, 40, 50, 60, 70, 80, 90, 100]
  - name: ether23
    comment: Trunk Native VLAN 10
    pvid: 10
    tagged: [20, 30, 40, 50, 60, 70, 80, 90, 100]
  - name: ether24
    comment: Trunk Native VLAN 10
    pvid: 10
    tagged: [20, 30, 40, 50, 60, 70, 80, 90, 100]
  - name: sfp-sfpplus1
    comment: Trunk port
    pvid: 10
    tagged: [10, 11,20, 30, 40, 50, 60, 70, 80, 90, 100]
  - name: sfp-sfpplus2
    comment: Trunk port
    pvid: 10
    tagged: [10, 11,20, 30, 40, 50, 60, 70, 80, 90, 100]