---
# CRS326-24G-2S+ USW1D specific settings

# Usw1d порты 7 и 8 на розетки 1d-G1 и 1d-G2 соответственно. 


bridge_port:
  - name: ether1
    comment: 1D-C-07 SKUD VIP01
    pvid: 20
  - name: ether2
    comment: 1D-C-17 SKUD VIP02
    pvid: 20
  - name: ether3
    comment: 1D-C-18 SKUD Right
    pvid: 20
  - name: ether4
    comment: Default Config
    pvid: 20
  - name: ether5
    comment: 1D-G-09 A5000 Entrance
    pvid: 20
  - name: ether6
    comment: Default Config
    pvid: 20
  - name: ether7
    comment: 1D-G-1 SKUD
    pvid: 20
  - name: ether8
    comment: 1D-G-2 SKUD
    pvid: 20
  - name: ether9
    comment: Default Config
    pvid: 20
  - name: ether10
    comment: Default Config
    pvid: 20
  - name: ether11
    comment: Default Config
    pvid: 20
  - name: ether12
    comment: Default Config
    pvid: 20
  - name: ether13
    comment: Default Config
    pvid: 20
  - name: ether14
    comment: Default Config
    pvid: 20
  - name: ether15
    comment: Default Config
    pvid: 20
  - name: ether16
    comment: Default Config
    pvid: 20
  - name: ether17
    comment: Trunk Native VLAN 10
    pvid: 10
    tagged: [20,30,40,50,60,70,80,90,100]
  - name: ether18
    comment: Trunk Native VLAN 10
    pvid: 10
    tagged: [20,30,40,50,60,70,80,90,100]
  - name: ether19
    comment: Trunk Native VLAN 10
    pvid: 10
    tagged: [20,30,40,50,60,70,80,90,100]
  - name: ether20
    comment: Trunk Native VLAN 10
    pvid: 10
    tagged: [20,30,40,50,60,70,80,90,100]
  - name: ether21
    comment: Trunk Native VLAN 10
    pvid: 10
    tagged: [20,30,40,50,60,70,80,90,100]
  - name: ether22
    comment: Trunk Native VLAN 10
    pvid: 10
    tagged: [20,30,40,50,60,70,80,90,100]
  - name: ether23
    comment: 1D-E-01 - USW2DEXPO Port 47
    pvid: 10
    tagged: [10, 20,30,40,50,60,70,80,90,100]
  - name: ether24
    comment: 1D-E-02 - USW2CEXPO Port 48
    pvid: 10
    tagged: [10, 20,30,40,50,60,70,80,90,100]
  - name: sfp-sfpplus1
    comment: Trunk port
    pvid: 10
    tagged: [10,11,20,30,40,50,60,70,80,90,100]
  - name: sfp-sfpplus2
    comment: Trunk port
    pvid: 10
    tagged: [10,11,20,30,40,50,60,70,80,90,100]