---
# CRS326-24G-2S+ USW2D specific settings
bridge_port:
  - name: ether1
    comment: 2D-B-1 - Main Hall
    pvid: 50
    edge: yes
    loop-protect: on
  - name: ether2
    comment: Vending Machine
    pvid: 70
    edge: yes
    loop-protect: on
    speed: 100
  - name: ether3
    comment: 2-nd floor. Hall near elev. Unifi U7PM35
    pvid: 10
    tagged: [11,20,30,40,50,60,70,80,90,100]
  - name: ether4
    comment: Default Config
    pvid: 70
    edge: yes
    loop-protect: on
  - name: ether5
    comment: Default Config
    pvid: 70
    edge: yes
    loop-protect: on
  - name: ether6
    comment: Default Config
    pvid: 70
    edge: yes
    loop-protect: on
  - name: ether7
    comment: Default Config
    pvid: 70
    edge: yes
    loop-protect: on
  - name: ether8
    comment: Default Config
    pvid: 70
    edge: yes
    loop-protect: on
  - name: ether9
    comment: Default Config
    pvid: 70
    edge: yes
    loop-protect: on
  - name: ether10
    comment: Default Config
    pvid: 70
    edge: yes
    loop-protect: on
  - name: ether11
    comment: Default Config
    pvid: 70
    edge: yes
    loop-protect: on
  - name: ether12
    comment: Default Config
    pvid: 70
    edge: yes
    loop-protect: on
  - name: ether13
    comment: Default Config
    pvid: 70
    edge: yes
    loop-protect: on
  - name: ether14
    comment: Default Config
    pvid: 70
    edge: yes
    loop-protect: on
  - name: ether15
    comment: Default Config
    pvid: 70
    edge: yes
    loop-protect: on
  - name: ether16
    comment: Default Config
    pvid: 70
    edge: yes
    loop-protect: on
  - name: ether17
    comment: Default Config
    pvid: 70
    edge: yes
    loop-protect: on
  - name: ether18
    comment: Default Config
    pvid: 70
    edge: yes
    loop-protect: on
  - name: ether19
    comment: Default Config
    pvid: 70
    edge: yes
    loop-protect: on
  - name: ether20
    comment: Default Config
    pvid: 70
    edge: yes
    loop-protect: on
  - name: ether21
    comment: Default Config
    pvid: 70
    edge: yes
    loop-protect: on
  - name: ether22
    comment: Default Config
    pvid: 70
    edge: yes
    loop-protect: on
  - name: ether23
    comment: U7PM53
    pvid: 10
    tagged: [11,20,30,40,50,60,70,80,90,100]
  - name: ether24
    comment: Default Config
    pvid: 70
    edge: yes
    loop-protect: on
  - name: sfp-sfpplus1
    comment: Trunk port
    pvid: 10
    tagged: [10,11,20,30,40,50,60,70,80,90,100]
  - name: sfp-sfpplus2
    comment: Trunk port
    pvid: 10
    tagged: [10,11,20,30,40,50,60,70,80,90,100]