---
# CRS354-48P-4S+2Q+ USW2DEXPO specific settings

bridge_port:
  - name: ether1
    comment: Stand 07. Gazprombank
    pvid: 70
    edge: yes
    loop-protect: on
  - name: ether2
    comment: Stand 08. T-Bank
    pvid: 70
    edge: yes
    loop-protect: on
  - name: ether3
    comment: Stand 07. Gazinformservice Unifi U7PM41
    pvid: 10
    tagged: [11,20,30,40,50,60,70,80,90,100]    
  - name: ether4
    comment: Stand 07. Gazinformservice
    pvid: 70
    edge: yes
    loop-protect: on
  - name: ether5
    comment: Stand 02. Sber
    pvid: 70
    edge: yes
    loop-protect: on
  - name: ether6
    comment: Stand 03. Positive Technologies 
    pvid: 70
    edge: yes
    loop-protect: on
  - name: ether7
    comment: Stand 02. Sber
    pvid: 70
    edge: yes
    loop-protect: on
  - name: ether8
    comment: Stand 00. Bank PSB
    pvid: 70
    edge: yes
    loop-protect: on
  - name: ether9
    comment: Stand 09. Garda
    pvid: 70
    edge: yes
    loop-protect: on
  - name: ether10
    comment: Stand 07. Gazinformservice
    pvid: 70
    edge: yes
    loop-protect: on
  - name: ether11
    comment: Stand 01. ScalaR
    pvid: 70
    edge: yes
    loop-protect: on
  - name: ether12
    comment: Stand 02. Sber
    pvid: 70
    edge: yes
    loop-protect: on
  - name: ether13
    comment: Default Config
    pvid: 70
    edge: yes
    loop-protect: on
  - name: ether14
    comment: Default Config
    pvid: 70
    edge: yes
    loop-protect: on
  - name: ether15
    comment: Stand 15. Flant
    pvid: 70
    edge: yes
    loop-protect: on
  - name: ether16
    comment: Stand 16. Axiom
    pvid: 70
    edge: yes
    loop-protect: on
  - name: ether17
    comment: Stand 17. Dialog Nauka
    pvid: 70
    edge: yes
    loop-protect: on
  - name: ether18
    comment: STAND 18. ITD Group 
    pvid: 70
    edge: yes
    loop-protect: on
  - name: ether19
    comment: Default Config
    pvid: 70
    edge: yes
    loop-protect: on
  - name: ether20
    comment: Default Config
    pvid: 70
    edge: yes
    loop-protect: on
  - name: ether21
    comment: Default Config
    pvid: 70
    edge: yes
    loop-protect: on
  - name: ether22
    comment: Default Config
    pvid: 70
    edge: yes
    loop-protect: on
  - name: ether23
    comment: Default Config
    pvid: 70
    edge: yes
    loop-protect: on
  - name: ether24
    comment: Default Config
    pvid: 70
    edge: yes
    loop-protect: on
  - name: ether25
    comment: Default Config
    pvid: 70
    edge: yes
    loop-protect: on
  - name: ether26
    comment: Default Config
    pvid: 70
    edge: yes
    loop-protect: on
  - name: ether27
    comment: Default Config
    pvid: 70
    edge: yes
    loop-protect: on
  - name: ether28
    comment: Default Config
    pvid: 70
    edge: yes
    loop-protect: on
  - name: ether29
    comment: Default Config
    pvid: 70
    edge: yes
    loop-protect: on
  - name: ether30
    comment: Default Config
    pvid: 70
    edge: yes
    loop-protect: on
  - name: ether31
    comment: Default Config
    pvid: 70
    edge: yes
    loop-protect: on
  - name: ether32
    comment: Default Config
    pvid: 70
    edge: yes
    loop-protect: on
  - name: ether33
    comment: Default Config
    pvid: 70
    edge: yes
    loop-protect: on
  - name: ether34
    comment: Default Config
    pvid: 70
    edge: yes
    loop-protect: on
  - name: ether35
    comment: Default Config
    pvid: 70
    edge: yes
    loop-protect: on
  - name: ether36
    comment: Default Config
    pvid: 70
    edge: yes
    loop-protect: on
  - name: ether37
    comment: Default Config
    pvid: 70
    edge: yes
    loop-protect: on
  - name: ether38
    comment: Default Config
    pvid: 70
    edge: yes
    loop-protect: on
  - name: ether39
    comment: Default Config
    pvid: 70
    edge: yes
    loop-protect: on
  - name: ether40
    comment: Default Config
    pvid: 70
    edge: yes
    loop-protect: on
  - name: ether41
    comment: Default Config
    pvid: 70
    edge: yes
    loop-protect: on
  - name: ether42
    comment: Default Config
    pvid: 70
    edge: yes
    loop-protect: on
  - name: ether43
    comment: Default Config
    pvid: 70
    edge: yes
    loop-protect: on
  - name: ether44
    comment: Default Config
    pvid: 70
    edge: yes
    loop-protect: on
  - name: ether45
    comment: Default Config
    pvid: 70
    edge: yes
    loop-protect: on
  - name: ether46
    comment: Default Config
    pvid: 70
    edge: yes
    loop-protect: on
  - name: ether47
    comment: Trunk port
    pvid: 10
    tagged: [10,11,20,30,40,50,60,70,80,90,100]
  - name: ether48
    comment: Trunk port
    pvid: 10
    tagged: [10,11,20,30,40,50,60,70,80,90,100]
  - name: ether49
    comment: Management port
    pvid: 10
  - name: qsfpplus1-1
    comment: Trunk port
    pvid: 10
    tagged: [10,11,20,30,40,50,60,70,80,90,100]
  - name: qsfpplus1-2
    comment: Trunk port
    pvid: 10
    tagged: [10,11,20,30,40,50,60,70,80,90,100]
  - name: qsfpplus1-3
    comment: Trunk port
    pvid: 10
    tagged: [10,11,20,30,40,50,60,70,80,90,100]
  - name: qsfpplus1-4
    comment: Trunk port
    pvid: 10
    tagged: [10,11,20,30,40,50,60,70,80,90,100]
  - name: qsfpplus2-1
    comment: Trunk port
    pvid: 10
    tagged: [10,11,20,30,40,50,60,70,80,90,100]
  - name: qsfpplus2-2
    comment: Trunk port
    pvid: 10
    tagged: [10,11,20,30,40,50,60,70,80,90,100]
  - name: qsfpplus2-3
    comment: Trunk port
    pvid: 10
    tagged: [10,11,20,30,40,50,60,70,80,90,100]
  - name: qsfpplus2-4
    comment: Trunk port
    pvid: 10
    tagged: [10,11,20,30,40,50,60,70,80,90,100]
  - name: sfp-sfpplus1
    comment: Trunk port
    pvid: 10
    tagged: [10,11,20,30,40,50,60,70,80,90,100]
  - name: sfp-sfpplus2
    comment: Trunk port
    pvid: 10
    tagged: [10,11,20,30,40,50,60,70,80,90,100]
  - name: sfp-sfpplus3
    comment: Trunk port
    pvid: 10
    tagged: [10,11,20,30,40,50,60,70,80,90,100]
  - name: sfp-sfpplus4
    comment: Trunk port
    pvid: 10
    tagged: [10,11,20,30,40,50,60,70,80,90,100]