---
# CRS326-24G-2S+ USW3M specific settings

# Чекалов Антон, [14.02.2026 13:55]
# USW3M Port 1 -> трансляция осн III
# USW3M Port 2 -> трансляция резерв II
# USW3M Port 3 -> бытовая сеть I

# Чекалов Антон, [14.02.2026 13:55]
# USW3M Port 4 -> 3M.1-B-08 -> U7PM33

bridge_port:
  - name: ether1
    comment: Hall 2. Broadcast Main
    pvid: 10
  - name: ether2
    comment: Hall 2. Broadcast Backup
    pvid: 11
  - name: ether3
    comment: Hall 2. Pult
    pvid: 50
    edge: yes
    loop-protect: on
  - name: ether4
    comment: 3M.1-B-08 Unifi U7PM33
    pvid: 10
    tagged: [11,20,30,40,50,60,70,80,90,100]
  - name: ether5
    comment: Default Config
    pvid: 70
    edge: yes
    loop-protect: on
  - name: ether6
    comment: Default Config
    pvid: 70
    edge: yes
    loop-protect: on
  - name: ether7
    comment: Default Config
    pvid: 70
    edge: yes
    loop-protect: on
  - name: ether8
    comment: Default Config
    pvid: 70
    edge: yes
    loop-protect: on
  - name: ether9
    comment: Default Config
    pvid: 70
    edge: yes
    loop-protect: on
  - name: ether10
    comment: Default Config
    pvid: 70
    edge: yes
    loop-protect: on
  - name: ether11
    comment: Default Config
    pvid: 70
    edge: yes
    loop-protect: on
  - name: ether12
    comment: Default Config
    pvid: 70
    edge: yes
    loop-protect: on
  - name: ether13
    comment: Default Config
    pvid: 70
    edge: yes
    loop-protect: on
  - name: ether14
    comment: Default Config
    pvid: 70
    edge: yes
    loop-protect: on
  - name: ether15
    comment: Default Config
    pvid: 70
    edge: yes
    loop-protect: on
  - name: ether16
    comment: Default Config
    pvid: 70
    edge: yes
    loop-protect: on
  - name: ether17
    comment: Default Config
    pvid: 70
    edge: yes
    loop-protect: on
  - name: ether18
    comment: Default Config
    pvid: 70
    edge: yes
    loop-protect: on
  - name: ether19
    comment: Default Config
    pvid: 70
    edge: yes
    loop-protect: on
  - name: ether20
    comment: Default Config
    pvid: 70
    edge: yes
    loop-protect: on
  - name: ether21
    comment: Default Config
    pvid: 70
    edge: yes
    loop-protect: on
  - name: ether22
    comment: Default Config
    pvid: 70
    edge: yes
    loop-protect: on
  - name: ether23
    comment: Management
    pvid: 10
  - name: ether24
    comment: Hall 2. Unifi U7PM45
    pvid: 10
    tagged: [11,20,30,40,50,60,70,80,90,100]
  - name: sfp-sfpplus1
    comment: Trunk port
    pvid: 10
    tagged: [10,11,20,30,40,50,60,70,80,90,100]
  - name: sfp-sfpplus2
    comment: Trunk port
    pvid: 10
    tagged: [10,11,20,30,40,50,60,70,80,90,100]