---
# CRS326-24G-2S+ USW3K specific settings


# Порт1: кабель Т1 - трансляция
# Порт2: кабель Т2 - трансляция        резерв.
# Порт3: кабель Б - бытовая сеть
# Порт24: кабель Точка 32 - точка U7PM32

bridge_port:
  - name: ether1
    comment: Hall 3 - Broadcast Backup
    pvid: 11
  - name: ether2
    comment: Hall 3 - Broadcast Main
    pvid: 10
  - name: ether3
    comment: Hall 3 - Tech network
    pvid: 50
  - name: ether4
    comment: Default Config
    pvid: 70
  - name: ether5
    comment: Default Config
    pvid: 70
  - name: ether6
    comment: Default Config
    pvid: 70
  - name: ether7
    comment: Default Config
    pvid: 70
  - name: ether8
    comment: Default Config
    pvid: 70
  - name: ether9
    comment: Default Config
    pvid: 70
  - name: ether10
    comment: Default Config
    pvid: 70
  - name: ether11
    comment: Default Config
    pvid: 70
  - name: ether12
    comment: Default Config
    pvid: 70
  - name: ether13
    comment: Default Config
    pvid: 70
  - name: ether14
    comment: Default Config
    pvid: 70
  - name: ether15
    comment: Default Config
    pvid: 70
  - name: ether16
    comment: Default Config
    pvid: 70
  - name: ether17
    comment: Default Config
    pvid: 70
  - name: ether18
    comment: Default Config
    pvid: 70
  - name: ether19
    comment: Default Config
    pvid: 70
  - name: ether20
    comment: Default Config
    pvid: 70
  - name: ether21
    comment: Default Config
    pvid: 70
  - name: ether22
    comment: Default Config
    pvid: 70
  - name: ether23
    comment: Management
    pvid: 10
  - name: ether24
    comment: Hall 3 - Unifi U7PM32
    pvid: 10
    tagged: [11,20,30,40,50,60,70,80,90,100]
  - name: sfp-sfpplus1
    comment: Trunk port
    pvid: 10
    tagged: [10,11,20,30,40,50,60,70,80,90,100]
  - name: sfp-sfpplus2
    comment: Trunk port
    pvid: 10
    tagged: [10,11,20,30,40,50,60,70,80,90,100]