---
# CRS326-24G-2S+ USW4C specific settings
bridge_port:
  - name: ether1
    comment: 4C-B-06 Hall 4.1 Unifi U6M24
    pvid: 10
    tagged: [11,20,30,40,50,60,70,80,90,100]
  - name: ether2
    comment: 4C-B-07 Hall 4.1 Pult
    pvid: 50
    edge: yes
    loop-protect: on
  - name: ether3
    comment: 4.2 Stab BoR Printer
    pvid: 60
    edge: yes
    loop-protect: on
  - name: ether4
    comment: 4.2 Stab BoR Printer
    pvid: 60
    edge: yes
    loop-protect: on
  - name: ether5
    comment: 4.2 Stab BoR TV VTZS
    pvid: 60
    edge: yes
    loop-protect: on  
  - name: ether6
    comment: Default Config
    pvid: 60
    edge: yes
    loop-protect: on
  - name: ether7
    comment: Default Config
    pvid: 60
    edge: yes
    loop-protect: on
  - name: ether8
    comment: Default Config
    pvid: 60
    edge: yes
    loop-protect: on
  - name: ether9
    comment: Default Config
    pvid: 60
    edge: yes
    loop-protect: on
  - name: ether10
    comment: Default Config
    pvid: 60
    edge: yes
    loop-protect: on
  - name: ether11
    comment: Default Config
    pvid: 60
    edge: yes
    loop-protect: on
  - name: ether12
    comment: Default Config
    pvid: 60
    edge: yes
    loop-protect: on
  - name: ether13
    comment: Default Config
    pvid: 60
    edge: yes
    loop-protect: on
  - name: ether14
    comment: Default Config
    pvid: 60
    edge: yes
    loop-protect: on
  - name: ether15
    comment: Default Config
    pvid: 60
    edge: yes
    loop-protect: on
  - name: ether16
    comment: Default Config
    pvid: 60
    edge: yes
    loop-protect: on
  - name: ether17
    comment: Default Config
    pvid: 60
    edge: yes
    loop-protect: on
  - name: ether18
    comment: Default Config
    pvid: 60
    edge: yes
    loop-protect: on
  - name: ether19
    comment: Default Config
    pvid: 60
    edge: yes
    loop-protect: on
  - name: ether20
    comment: Default Config
    pvid: 60
    edge: yes
    loop-protect: on
  - name: ether21
    comment: Default Config
    pvid: 60
    edge: yes
    loop-protect: on
  - name: ether22
    comment: Default Config
    pvid: 60
    edge: yes
    loop-protect: on
  - name: ether23
    comment: Management
    pvid: 10
  - name: ether24
    comment: Unifi U6E07
    pvid: 10
    tagged: [11,20,30,40,50,60,70,80,90,100]
  - name: sfp-sfpplus1
    comment: Trunk port
    pvid: 10
    tagged: [10,11,20,30,40,50,60,70,80,90,100]
  - name: sfp-sfpplus2
    comment: Trunk port
    pvid: 10
    tagged: [10,11,20,30,40,50,60,70,80,90,100]