---
# USWG1B specific settings
bridge_port:
  - name: ether1
    comment: 1.B.1.2.14
    pvid: 70
  - name: ether2
    comment: 1.B.1.2.15
    pvid: 70
  - name: ether3
    comment: 1.B.1.5.22
    pvid: 20
  - name: ether4
    comment: 1.B.1.5.19
    pvid: 70
  - name: ether5
    comment: 1.B.1.5.20
    pvid: 70
  - name: ether6
    comment: 1.B.1.1.11
    pvid: 70
  - name: ether7
    comment: 1.B.1.1.12
    pvid: 70
  - name: ether8
    comment: 1.B.1.4.15
    pvid: 70
  - name: ether9
    comment: 1.B.1.4.16
    pvid: 70
  - name: ether10
    comment: 1.B.1.5.7
    pvid: 70
  - name: ether11
    comment: 1.B.1.5.9
    pvid: 70
  - name: ether12
    comment: 1.B.1.5.13
    pvid: 20
  - name: ether13
    comment: 1.B.1.5.17
    pvid: 70
  - name: ether14
    comment: 1.B.1.5.8
    pvid: 70
  - name: ether15
    comment: 1.B.1.5.10
    pvid: 70
  - name: ether16
    comment: 1.B.1.5.14
    pvid: 20
  - name: ether17
    comment: 1.B.2.2.22
    pvid: 70
  - name: ether18
    comment: 1.B.1.1.1
    pvid: 70
  - name: ether19
    comment: 1.B.1.1.2
    pvid: 70
  - name: ether20
    comment: 1.B.1.4.14-SKUD    
    pvid: 10
    tagged: [20,30,40,50,60,70,80,90]
  - name: ether21
    comment: Default Config
    pvid: 70
  - name: ether22
    comment: Default Config
    pvid: 70
  - name: ether23
    comment: Default Config
    pvid: 70
  - name: ether24
    comment: Trunk Native VLAN 10
    pvid: 10
    tagged: [20,30,40,50,60,70,80,90]
  - name: sfp-sfpplus1
    comment: SWG02-sfpplus5
    pvid: 10
    tagged: [10,20,30,40,50,60,70,80,90]
  - name: sfp-sfpplus2
    comment: SWG01-sfpplus5
    pvid: 10
    tagged: [10,20,30,40,50,60,70,80,90]