---
# USWGBKZ01 specific settings
bridge_port:
  - name: ether1
    comment: R1.1.02.04-SKUD Stage
    pvid: 20
  - name: ether2
    comment: R1.1.02.05-SKUD Stage
    pvid: 20
  - name: ether3
    comment: R1.1.02.14-SKUD Stage
    pvid: 20
  - name: ether4
    comment: R1.1.02.15-SKUD Stage
    pvid: 20
  - name: ether5
    comment: BKZ-SKUD05 PULT
    pvid: 20
  - name: ether6
    comment: SKUD06 Office
    pvid: 20
  - name: ether7
    comment: RZL Backup
    pvid: 11
  - name: ether8
    comment: Default Config
    pvid: 50
  - name: ether9
    comment: Default Config
    pvid: 50
  - name: ether10
    comment: Default Config
    pvid: 50
  - name: ether11
    comment: Default Config
    pvid: 50
  - name: ether12
    comment: Default Config
    pvid: 50
  - name: ether13
    comment: Default Config
    pvid: 10
  - name: sfp-sfpplus1
    comment: Trunk port
    pvid: 10
    tagged: [10,11,20,30,40,50,60,70,80,90,100]
  - name: sfp-sfpplus2
    comment: Trunk port
    pvid: 10
    tagged: [10,11,20,30,40,50,60,70,80,90,100]
  - name: sfp-sfpplus3
    comment: Trunk port
    pvid: 10
    tagged: [10,11,20,30,40,50,60,70,80,90,100]
  - name: sfp-sfpplus4
    comment: Trunk port
    pvid: 10
    tagged: [10,11,20,30,40,50,60,70,80,90,100]